### ISSUE TITLE
Delete Repository?

### ISSUE THREAD

**Issue by jonnyarnold** [reevoo/virtus#1]
This is behind the solnic version. Do we even use this?

**Comment by lpil** [comment]
I think it was just used to make a PR.

https://github.com/solnic/virtus/commit/c2dc794e22d1da559e42462d6220595e115b9985

**Comment by jonnyarnold** [comment]
Lovely. Thanks @lpil :)

**Comment by jonnyarnold** [comment]
Used by Reports, Insight + Data Service. Not sure we want to touch them. We should reconsider removing this when they go out of service.
